### PR TITLE
use name instead of method in the snapshot

### PR DESCRIPTION
**Pull request by sarahBuisson**
following my suggestion : https://github.com/origin-energy/java-snapshot-testing/issues/95

It endup being quite easy to implement, and seem to be fully transparent for the existing.

Warning : I don't have project to test it currently. Please clone my branch and test it before merging!

### CODE REVIEW

**Comment by bjuric** [comment]
@jackmatt2 Did you want to have a quick look at this one?

**Comment by jackmatt2** [comment]
I don't think this is required as we already have the `@SnapshotName("foobar")` annotation

**Comment by bjuric** [comment]
@sarahBuisson, have you had a chance to try the `@Snapshot` annotation as per @jackmatt2's comment?

**Comment by bjuric** [comment]
Closing since there has been no response from the submitter.

**Pull request closed without merging**
